### ISSUE TITLE
||PaMacCore (AUHAL)|| error on line 1316: err='-66748', msg=Unknown error" 

### ISSUE THREAD

**Issue by mariomanalu** [PortAudio/portaudio#514]
**Describe the bug**
I get "||PaMacCore (AUHAL)|| error on line 1316: err='-66748', msg=Unknown error" when trying to run the speak program from eSpeak. 

**To Reproduce**
Steps to reproduce the behavior. Include code if applicable.
1. Download and compile eSpeak
2. ./speak "Test"

**Expected behavior**
The program should say "test"

**Actual behavior**
error. ||PaMacCore (AUHAL)|| error on line 1316: err='-66748', msg=Unknown error" 

**Desktop (please complete the following information):**
 - OS: Mac OS
 - OS Version: 11.1 (Big Sur)
 - PortAudio version: stable 

**Additional context**
I am trying to run the eSpeak program using portaudio, and I am getting the error outlined in the title. I know someone else encountered a similar problem, and they solved it by reinstalling portaudio using the --HEAD flag. I did that, but it has not worked. FYI, I am using a Big Sur machine on Apple M1 processor.

**Comment by rryan** [comment]
Error code 66748 is kAudioComponentErr_NotPermitted.

On Big Sur (maybe earlier versions), the app needs Microphone permissions. I haven't figured out how to add permissions for a standalone binary.

https://support.apple.com/en-gb/HT209175

I'm fighting with the same issue right now trying to use pyaudio. I think what I need to do is get Python to have microphone permissions. I've already gotten my terminal apps added to the list and that hasn't helped.

**Comment by rryan** [comment]
This is fixed at head for me -- after building portaudio from head, my pyaudio Python script caused a macOS microphone permission challenge and it was able to access my microphone fine after that.

**Comment by philburk** [comment]
@rryan - Thanks for the report. I see the OP was using the "stable" release. Soon HEAD will be the new "stable" 19.7.
I am closing since this seems to be fixed in master.

**Comment by pythlang** [comment]
Can you please advise how or when this will be fixed? Also on Big Sur and traced it back to this small thread, but I'm unable to fix.

Thanks for the help.

**Comment by philburk** [comment]
It is fixed in our master. But brew and other sites will need to update their installation packages after we release 19.7.
We will release when we resolve these issues:
https://github.com/PortAudio/portaudio/milestone/9

**Comment by pythlang** [comment]
> It is fixed in our master. But brew and other sites will need to update their installation packages after we release 19.7.
> We will release when we resolve these issues:
> https://github.com/PortAudio/portaudio/milestone/9

I realized what this meant later when it occurred that brew is downstream from you.

thanks a lot for the update. Do you know the typical lead time for something like that to happen? 

Thanks again

**Comment by pdeitel** [comment]
I have portaudio 19.7 installed and still getting 

||PaMacCore (AUHAL)|| Error on line 1277: err='-66748', msg=Unknown Error

and

OSError: [Errno -9986] Internal PortAudio error

when I run a Python script. Any ideas?
